Repository AY1920S1-CS2103T-W13-1/main, pull requests merged in 2019-10, with the labels that each got.

#13 Updated README.adoc
  README.adoc
  docs/images/Ui.png
Labels: type.Documentation

#9 Update developer guide
  docs/DeveloperGuide.adoc
Labels: type.Documentation

#27 Add ArchivedModule and Storage support
  src/main/java/seedu/module/MainApp.java
  src/main/java/seedu/module/commons/util/JsonUtil.java
  src/main/java/seedu/module/model/ModuleBook.java
  src/main/java/seedu/module/model/ReadOnlyModuleBook.java
  src/main/java/seedu/module/model/module/ArchivedModule.java
  src/main/java/seedu/module/model/module/ArchivedModuleList.java
  src/main/java/seedu/module/model/util/SampleDataUtil.java
  src/main/java/seedu/module/storage/JsonAdaptedArchivedModule.java
  src/main/java/seedu/module/storage/JsonArchivedModuleList.java
  src/main/java/seedu/module/storage/JsonModuleBookStorage.java
  src/main/java/seedu/module/storage/ModuleBookStorage.java
  src/main/java/seedu/module/storage/Storage.java
  src/main/java/seedu/module/storage/StorageManager.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonModuleBookStorageTest/invalidAndValidModuleModuleBook.json
  src/test/data/JsonModuleBookStorageTest/invalidModuleModuleBook.json
  src/test/data/JsonModuleBookStorageTest/notJsonFormatModuleBook.json
  src/test/java/seedu/module/commons/util/JsonUtilTest.java
  src/test/java/seedu/module/model/module/ArchivedModuleListTest.java
  src/test/java/seedu/module/model/module/ArchivedModuleTest.java
  src/test/java/seedu/module/storage/JsonAdaptedArchivedModuleTest.java
  src/test/java/seedu/module/storage/JsonArchivedModuleListTest.java
  src/test/java/seedu/module/testutil/ArchivedModuleBuilder.java
  src/test/java/seedu/module/testutil/SerializableTestClass.java
  src/test/resources/data/archivedModules.json
Labels: priority.High, type.Story

#33 Add and delete command
  src/main/java/seedu/module/MainApp.java
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/DeleteCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/ArchiveStub.java
  src/main/java/seedu/module/model/ModuleBook.java
  src/main/java/seedu/module/model/module/NameContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/TrackedModule.java
  src/main/java/seedu/module/model/util/SampleDataUtil.java
  src/main/java/seedu/module/storage/JsonAdaptedModule.java
  src/main/java/seedu/module/storage/JsonModuleBookStorage.java
  src/main/java/seedu/module/storage/JsonSerializableModuleBook.java
  src/main/java/seedu/module/storage/ModuleBookStorage.java
  src/main/java/seedu/module/storage/Storage.java
  src/main/java/seedu/module/storage/StorageManager.java
Labels: priority.High, type.Story

#26 Fix image not showing in github website
  README.adoc
Labels: severity.Low, type.Bug

#29 Update ModelClassDiagram and DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: priority.Low, type.Documentation

#46 Implement Module Viewing Feature
  build.gradle
  src/main/java/seedu/module/logic/Logic.java
  src/main/java/seedu/module/logic/LogicManager.java
  src/main/java/seedu/module/logic/commands/BackCommand.java
  src/main/java/seedu/module/logic/commands/CommandResult.java
  src/main/java/seedu/module/logic/commands/ExitCommand.java
  src/main/java/seedu/module/logic/commands/HelpCommand.java
  src/main/java/seedu/module/logic/commands/ViewCommand.java
  src/main/java/seedu/module/logic/parser/ModuleBookParser.java
  src/main/java/seedu/module/logic/parser/ViewCommandParser.java
  src/main/java/seedu/module/model/Model.java
  src/main/java/seedu/module/model/ModelManager.java
  src/main/java/seedu/module/ui/HomeViewPanel.java
  src/main/java/seedu/module/ui/MainWindow.java
  src/main/java/seedu/module/ui/ModuleViewPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HomeViewPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleViewPanel.fxml
  src/test/java/seedu/module/logic/commands/BackCommandTest.java
  src/test/java/seedu/module/logic/commands/CommandResultTest.java
  src/test/java/seedu/module/logic/commands/ExitCommandTest.java
  src/test/java/seedu/module/logic/commands/HelpCommandTest.java
  src/test/java/seedu/module/logic/commands/ViewCommandTest.java
Labels: priority.High, type.Story

#30 Update StorageClassDiagram and DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: priority.Low, type.Documentation

#56 Add extra check to run travis check scripts
  build.gradle
Labels: priority.Medium, type.Task

#52 Cleanup DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: priority.Medium, type.Documentation

#47 Update UG and DG for Module View Feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModuleViewSequenceDiagram.puml
  docs/diagrams/ModuleViewSequenceDiagram_FindModule.puml
  docs/images/ModuleViewSequenceDiagram.png
  docs/images/ModuleViewSequenceDiagram_FindModule.png
Labels: priority.Medium, type.Documentation

#59 Cleanup docs to remove references to addressbook
  docs/DevOps.adoc
  docs/Documentation.adoc
  docs/Testing.adoc
  docs/templates/_header.html.slim
Labels: priority.Low, type.Documentation, type.Task

#55 Fix and Update tests for logic package
  src/main/java/seedu/module/logic/commands/CommandResult.java
  src/main/java/seedu/module/logic/parser/ViewCommandParser.java
  src/test/java/seedu/module/logic/LogicManagerTest.java
  src/test/java/seedu/module/logic/commands/CommandResultTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
  src/test/java/seedu/module/logic/parser/ViewCommandParserTest.java
Labels: priority.Low, severity.Low, type.Enhancement, type.Task

#62 Update Module View Documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/ModuleViewSequenceDiagram.puml
  docs/diagrams/ModuleViewSequenceDiagram_FindModule.puml
  docs/images/ModuleViewSequenceDiagram.png
  docs/images/ModuleViewSequenceDiagram_FindModule.png
Labels: priority.Low, type.Documentation

#67 Revert default plantuml fontsize change
  docs/diagrams/style.puml
Labels: priority.Low, type.Bug

#69 Update tests for storage package
  src/main/java/seedu/module/storage/JsonModuleBookStorage.java
  src/main/java/seedu/module/storage/ModuleBookStorage.java
  src/test/data/JsonModuleBookStorageTest/invalidAndValidModuleModuleBook.json
  src/test/data/JsonModuleBookStorageTest/invalidModuleModuleBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableModuleBookTest/duplicateModuleModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/invalidModuleModuleBook.json
  src/test/data/JsonSerializableModuleBookTest/typicalModuleModuleBook.json
  src/test/java/seedu/module/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/module/storage/JsonModuleBookStorageTest.java
  src/test/java/seedu/module/storage/JsonSerializableModuleBookTest.java
  src/test/java/seedu/module/storage/StorageManagerTest.java
Labels: priority.Low, type.Task

#70 Refactor Add command.
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/ViewCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/model/Model.java
  src/main/java/seedu/module/model/ModelManager.java
  src/main/java/seedu/module/model/module/SameModuleCodePredicate.java
  src/test/java/seedu/module/logic/commands/AddCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
Labels: priority.Medium

#71 Re implement delete command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/module/logic/commands/DeleteCommand.java
  src/main/java/seedu/module/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/module/logic/LogicManagerTest.java
  src/test/java/seedu/module/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/module/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
Labels: priority.Low

#72 Add more fields to Module View
  src/main/java/seedu/module/model/module/ArchivedModule.java
  src/main/java/seedu/module/model/module/Module.java
  src/main/java/seedu/module/model/module/SemesterDetail.java
  src/main/java/seedu/module/model/module/SemesterDetailList.java
  src/main/java/seedu/module/model/module/TrackedModule.java
  src/main/java/seedu/module/storage/JsonAdaptedArchivedModule.java
  src/main/java/seedu/module/storage/JsonAdaptedSemesterDetail.java
  src/main/java/seedu/module/ui/ModuleSemesterDetailCard.java
  src/main/java/seedu/module/ui/ModuleViewPanel.java
  src/main/resources/view/ModuleSemesterDetail.fxml
  src/main/resources/view/ModuleViewPanel.fxml
  src/test/java/seedu/module/logic/LogicManagerTest.java
  src/test/java/seedu/module/logic/commands/BackCommandTest.java
  src/test/java/seedu/module/logic/commands/ViewCommandTest.java
  src/test/java/seedu/module/model/ModelManagerTest.java
  src/test/java/seedu/module/model/ModuleBookTest.java
  src/test/java/seedu/module/storage/JsonAdaptedArchivedModuleTest.java
  src/test/java/seedu/module/storage/JsonArchivedModuleListTest.java
  src/test/java/seedu/module/testutil/ArchivedModuleBuilder.java
  src/test/java/seedu/module/testutil/ArchivedModuleListBuilder.java
  src/test/java/seedu/module/testutil/ModuleBookBuilder.java
Labels: priority.Medium, type.Story

#74 Filtered search
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/module/commons/core/Messages.java
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/DeleteCommand.java
  src/main/java/seedu/module/logic/commands/FindCommand.java
  src/main/java/seedu/module/logic/commands/ViewCommand.java
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/module/logic/parser/FindCommandParser.java
  src/main/java/seedu/module/model/Model.java
  src/main/java/seedu/module/model/ModelManager.java
  src/main/java/seedu/module/model/module/ArchivedModule.java
  src/main/java/seedu/module/model/module/Module.java
  src/main/java/seedu/module/model/module/TrackedModule.java
  src/main/java/seedu/module/model/module/predicate/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/predicate/ModuleCodeContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/predicate/PreclusionContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/predicate/PrerequisiteContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/predicate/SameModuleCodePredicate.java
  src/main/java/seedu/module/model/module/predicate/SemesterContainsKeywordsPredicate.java
  src/test/java/seedu/module/logic/commands/AddCommandTest.java
  src/test/java/seedu/module/logic/commands/CommandTestUtil.java
  src/test/java/seedu/module/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/module/logic/commands/FindCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/module/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ModuleBookParserTest.java
Labels: priority.Medium

#78 Fix datetime stuck in UTC
  src/main/java/seedu/module/ui/ModuleSemesterDetailCard.java
Labels: priority.Low, type.Bug, type.Task

#80 Update user guide and Ui.png for 1.3
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: priority.High, type.Task
