Repository AY1920S1-CS2103T-W13-1/main, pull requests merged in 2019-11, with the labels that each got.

#118 Resolve issues from feedback.
  docs/UserGuide.adoc
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/parser/FindCommandParser.java
  src/main/java/seedu/module/model/module/predicate/TitleContainsKeywordsPredicate.java
Labels: priority.High

#141 Add text wrap to result display
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Low, severity.Low, type.Bug, type.Task

#142 Refactor module list and add tracking status
  src/main/java/seedu/module/logic/commands/AddCommand.java
  src/main/java/seedu/module/logic/commands/DeleteCommand.java
  src/main/java/seedu/module/logic/commands/FindCommand.java
  src/main/java/seedu/module/logic/commands/ListCommand.java
  src/main/java/seedu/module/logic/commands/deadlinecommands/AddDeadlineCommand.java
  src/main/java/seedu/module/logic/commands/deadlinecommands/DeleteDeadlineTaskCommand.java
  src/main/java/seedu/module/logic/commands/deadlinecommands/DoneDeadlineCommand.java
  src/main/java/seedu/module/logic/commands/deadlinecommands/EditDeadlineDescCommand.java
  src/main/java/seedu/module/logic/commands/deadlinecommands/EditDeadlineTimeCommand.java
  src/main/java/seedu/module/logic/commands/deadlinecommands/InProgressDeadlineCommand.java
  src/main/java/seedu/module/model/DisplayedModuleList.java
  src/main/java/seedu/module/model/Model.java
  src/main/java/seedu/module/model/ModelManager.java
  src/main/java/seedu/module/model/module/ArchivedModule.java
  src/main/java/seedu/module/model/module/ArchivedModuleList.java
  src/main/java/seedu/module/model/module/Module.java
  src/main/java/seedu/module/model/module/TrackedModule.java
  src/main/java/seedu/module/ui/ModuleCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ModuleListCard.fxml
  src/test/java/seedu/module/logic/LogicManagerTest.java
  src/test/java/seedu/module/logic/commands/AddCommandTest.java
  src/test/java/seedu/module/model/ModelManagerTest.java
  src/test/java/seedu/module/model/module/ArchivedModuleListTest.java
  src/test/java/seedu/module/model/module/ArchivedModuleTest.java
  src/test/java/seedu/module/model/module/ModuleTest.java
Labels: priority.Medium, type.Enhancement, type.Story

#144 Update GUi
  src/main/java/seedu/module/ui/ModuleViewPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HomeViewPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleSemesterDetail.fxml
  src/main/resources/view/ModuleViewPanel.fxml
Labels: priority.Medium, type.Enhancement

#148 Fuzzy search
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/module/logic/parser/FindCommandParser.java
  src/main/java/seedu/module/model/module/predicate/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/predicate/LevenshteinDistanceChecker.java
  src/main/java/seedu/module/model/module/predicate/TitleContainsKeywordsPredicate.java
  src/main/java/seedu/module/ui/SearchWindow.java
  src/test/java/seedu/module/logic/parser/LevenshteinDistanceCheckerTest.java
Labels: priority.Medium

#152 Add onClick handler to moduleListCell
  docs/UserGuide.adoc
  docs/images/ViewCommandGuiStep1.png
  docs/images/ViewCommandGuiStep2.png
  src/main/java/seedu/module/logic/Logic.java
  src/main/java/seedu/module/logic/LogicManager.java
  src/main/java/seedu/module/ui/MainWindow.java
  src/main/java/seedu/module/ui/ModuleCard.java
  src/main/java/seedu/module/ui/ModuleListPanel.java
  src/test/java/seedu/module/logic/LogicManagerTest.java
Labels: priority.Medium, type.Story

#153 Add sample data
  src/main/java/seedu/module/model/util/SampleDataUtil.java
  src/main/java/seedu/module/storage/JsonModuleBookStorage.java
  src/test/java/seedu/module/storage/JsonModuleBookStorageTest.java
Labels: priority.Medium, type.Enhancement

#154 Add accordions
  src/main/java/seedu/module/ui/ModuleViewPanel.java
  src/main/resources/view/ModuleViewPanel.fxml
Labels: priority.Medium, type.Enhancement

#156 Optimised search
  docs/UserGuide.adoc
  src/main/java/seedu/module/logic/parser/FindCommandParser.java
  src/main/java/seedu/module/model/module/predicate/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/module/model/module/predicate/LevenshteinDistanceChecker.java
  src/main/java/seedu/module/model/module/predicate/TitleContainsKeywordsPredicate.java
  src/test/java/seedu/module/logic/parser/LevenshteinDistanceCheckerTest.java
Labels: priority.High

#158 Fix images not showing on UG
  docs/UserGuide.adoc
Labels: severity.Medium, type.Bug, type.Documentation

#159 Update DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ModuleStatusClassDiagram.puml
  docs/diagrams/ModuleViewFindModuleActivityDiagram.puml
  docs/diagrams/ModuleViewSequenceDiagram_FindModule.puml
  docs/diagrams/style.puml
  docs/images/ModuleStatusClassDiagram.png
  docs/images/ModuleViewFindModuleActivityDiagram.png
  docs/images/ModuleViewSequenceDiagram_FindModule.png
Labels: priority.Medium, type.Documentation

#161 Update UG
  docs/UserGuide.adoc
  docs/images/userguide/Glossary_ArchivedModule.png
  docs/images/userguide/Glossary_HomeView.png
  docs/images/userguide/Glossary_ModuleView.png
  docs/images/userguide/Glossary_TrackedModule.png
  docs/images/userguide/ViewCommandGuiStep1.png
  docs/images/userguide/ViewCommandGuiStep2.png
Labels: priority.Medium, type.Documentation

#163 Update Ui.png
  docs/images/Ui.png
Labels: priority.Medium, type.Documentation

#164 Update css for website
  docs/stylesheets/asciidoctor.css
Labels: priority.Medium, type.Documentation

#166 Added test cases for predicates.
  src/main/java/seedu/module/model/module/predicate/SameModuleCodePredicate.java
  src/test/java/seedu/module/logic/commands/ClearCommandTest.java
  src/test/java/seedu/module/model/module/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/module/model/module/predicate/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/module/model/module/predicate/ModuleCodeContainsKeywordsPredicateTest.java
  src/test/java/seedu/module/model/module/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/module/model/module/predicate/PreclusionContainsKeywordsPredicateTest.java
  src/test/java/seedu/module/model/module/predicate/PrerequisiteContainsKeywordsPredicateTest.java
  src/test/java/seedu/module/model/module/predicate/SameModuleCodePredicateTest.java
  src/test/java/seedu/module/model/module/predicate/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/module/testutil/ArchivedModuleBuilder.java
Labels: priority.Low

#171 Fix issue when too many arguments are given to some commands
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/module/logic/parser/ViewCommandParser.java
Labels: priority.High, severity.Medium, type.Bug

#170 Update ModuleViewFindModuleActivityDiagram
  docs/diagrams/ModuleViewFindModuleActivityDiagram.puml
  docs/images/ModuleViewFindModuleActivityDiagram.png
Labels: priority.Medium, type.Documentation

#167 Add PPP
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/team/geshuming.adoc
Labels: priority.High, type.Documentation

#173 Changed how SameModuleCodePredicate works.
  src/main/java/seedu/module/logic/parser/AddCommandParser.java
  src/main/java/seedu/module/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/module/logic/parser/ViewCommandParser.java
  src/main/java/seedu/module/model/module/predicate/SameModuleCodePredicate.java
Labels: priority.High

#175 Updated UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/SearchActivityDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/SearchActivityDiagram.png
  docs/images/userguide/SearchGui.PNG
Labels: priority.Medium, type.Documentation

#172 Update tests
  src/test/java/seedu/module/logic/commands/BackCommandTest.java
  src/test/java/seedu/module/logic/commands/ListCommandTest.java
  src/test/java/seedu/module/logic/commands/ViewCommandTest.java
  src/test/java/seedu/module/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/module/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/module/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/module/model/module/ModuleTest.java
  src/test/java/seedu/module/model/module/SemesterDetailListTest.java
Labels: priority.Low, type.Enhancement

#168 Update sample data
  docs/images/Ui.png
  src/main/java/seedu/module/model/util/SampleDataUtil.java
Labels: priority.Medium, type.Enhancement

#181 Do not display urls in html to pdf conversion
  docs/stylesheets/gh-pages.css
Labels: priority.High, type.Documentation

#182 Fix screenshot not showing up on website.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/userguide/SearchGui.png
Labels: priority.Medium, type.Documentation

#183 Update PPP
  docs/team/geshuming.adoc
Labels: priority.High, type.Documentation

#187 Updated sequence diagram and corrected some grammar.
  docs/UserGuide.adoc
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/team/cowsaysbaa.adoc
Labels: priority.Medium, type.Documentation

#188 Update UG and DG for 1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Documentation

#189 Fixed some minor grammatical mistakes.
  docs/team/cowsaysbaa.adoc
Labels: type.Documentation

#191 Cleanup UG
  docs/UserGuide.adoc
Labels: priority.Medium, type.Documentation

#193 Update AboutUs
  docs/AboutUs.adoc
Labels: priority.Medium, type.Documentation

#194 Added Class diagram to find.
  docs/DeveloperGuide.adoc
  docs/diagrams/FindCommandClassDiagram.puml
  docs/images/FindCommandClassDiagram.png
Labels: type.Documentation

#195 Resized class diagram for find.
  docs/images/FindCommandClassDiagram.png
Labels: type.Documentation
